### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Woile** [Woile/commitizen#7]
## For release `1.0.0`:

- [x] promptkit 2.0
- [x] >~ 90% test coverage (almost done)
- [x] use [conventional commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) new tags + [this](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional) (almost done)
- [x] make use of `pyproject.toml` for dependencies tracking
- [x] support python `>3.6` only
- [x] make BaseCz importable from `commitizen.BaseCz` so it can be move around internally and there are no issue.
- [x]  update docs

## For release `1.1.0`:

- [x] add support for `pyproject.toml` configuration
- [x] auto bump version using semver and git tag:
get current version (either using git or cfg)
get commits since last tag
get max commit
map:
```
BREAKING CHANGE -> MAJOR
feat -> MINOR
fix/docs/ci/build/etc -> PATCH
```
Semver: `MAJOR.MINOR.PATCH`
it's important to support a manual tag, and maybe support for pre-releases (alpha, beta, etc)

## For release `1.6.0`:

- [ ] initial auto-changelog interface
- [ ] first draft for conventional commits autochangelog generation

Doubting:
- [ ] new command to generate template for a plugin

**Comment by NonWhite** [comment]
Hi, do you have any idea when will be ready new releases?

**Comment by Woile** [comment]
Sorry NonWhite, I've been really busy, I'll merge the currently open PR and I'll make a beta version.
I'll share here and you'll be able to test it.

**Comment by Woile** [comment]
@NonWhite I've ublished v1.0.0b1 feel free to test it and report if you find any issue.

`pip install -U commitizen==1.0.0b1`

**Comment by NonWhite** [comment]
great! thanks!
